name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_widget:
    path: ../
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_redux: ^0.10.0
  #html tag parser
  html: ^0.15.0
  #math equation rendering
  flutter_math_fork: ^0.6.3+1

  # for 'video' tag
  video_player: ^2.4.10

flutter:

  uses-material-design: true

  assets:
    - assets/