name: markdown_widget
description: A new markdown package. It supports TOC function, HTML video and img tag，and it works well on both the web and mobile
version: 1.3.0+2
verified publisher:
  - agedchen@gmail.com
homepage: https://github.com/asjqkkkk/markdown_widget

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #markdown data parser
  markdown: ^6.0.1
  #highlight code
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0


  # to click link
  url_launcher: ^6.1.7
  # to get the index number on scroll for listview
  visibility_detector: ^0.3.3
  # make listview available to jump to index
  scroll_to_index: ^3.0.1


  # for TOC
#  scrollable_positioned_list: ^0.3.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  build_runner: ^2.3.3
flutter:
