name: markdown_widget
description: A new markdown package. It supports TOC function, HTML video and img tag，and it works well on both the web and mobile
version: 1.3.0+2
verified publisher:
  - agedchen@gmail.com
homepage: https://github.com/asjqkkkk/markdown_widget

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #markdown data parser
  markdown: ^6.0.0
  #highlight code
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

  #html tag parser
  html: ^0.15.0

  # for 'video' tag
  video_player_web: ^2.0.10
  video_player: ^2.4.2
  collection: ^1.16.0

  # for TOC
#  scrollable_positioned_list: ^0.3.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
