name: Flutter Web
on:
  push:
    branches:
      - action_test
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.ACTION_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.0
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'dev'
      - run: ls
      - run: cd example && ls && flutter config --enable-web && flutter pub get && flutter build web --release
      - uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTION_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./markdown_widget/example/build/web